version: '3.5'

services:
  contracts-env:
    build:
      context: ./
    working_dir: /src
    command: npm run run-env
    env_file:
      - .env
    volumes:
      - ./:/src
      - $HOME/.tenderly/config.yaml:/root/.tenderly/config.yaml
    environment:
      MNEMONIC: ${MNEMONIC}
      ETHERSCAN_KEY: ${ETHERSCAN_KEY}
      INFURA_KEY: ${INFURA_KEY}
      ETHERSCAN_NETWORK: ${ETHERSCAN_NETWORK}
      GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}
      TENDERLY_PROJECT: ${TENDERLY_PROJECT}
      TENDERLY_USERNAME: ${TENDERLY_USERNAME}
      TENDERLY_FORK_ID: ${TENDERLY_FORK_ID}
      TENDERLY_HEAD_ID: ${TENDERLY_HEAD_ID}
